package sonnh.opt.opt_plan.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.UUID;

@Entity
@Table(name = "payment_methods")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class PaymentMethod {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long id;

	@Column(nullable = false, unique = true)
	private String code;

	@Column(nullable = false)
	private String name;

	/**
	 * Generates a unique code for the payment method based on the name. The
	 * code is generated by concatenating the first three characters of the name
	 * with a unique identifier. This approach ensures that the code is unique
	 * and can be used to identify the payment method.
	 * 
	 * @param name The name of the payment method.
	 * @return A unique code for the payment method.
	 */
	public static String generateCode(String name) {
		return name.substring(0, 3) + UUID.randomUUID().toString().substring(0, 8);
	}
}
